---
title: 'Case Study 1: Data Visualization'
---

```{r, echo=FALSE, include=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)
```


# Learning Objectives

- gain programming skills in RStudio
- gain skills in data wrangling techniques, including combining data across a variety of sources and formats, data harmonization, and creation of new variables
- create effective visual displays of complex information using R and Tableau
- create interactive visual presentations using Tableau


# Case Study Goals

Using global health data from the World Bank, CIA Factbook, or a complex data source of your own choosing, 

- produce compelling R graphics communicating an aspect of our world in data
- create a Tableau dashboard interactive visual presentation to illustrate an aspect of our world in data
- communicate your graphical findings in a dynamic class presentation

# Data 

- North Carolina Birth Records: these data cannot be shared beyond class participants. Please see Sakai (Resources) for the data and related documentation, and do not disseminate the data any further.
- Worldwide country-level data on maternal and infant outcomes: publicly available

- [popDF.RData](decks/data/popDF.RData)

- [infMortDF.RData](decks/data/infMortDF.RData)

- [codeMapDF.RData](decks/data/codeMapDF.RData)

- [allCtryData.RData](decks/data/allCtryData.RData)

- [full.RData](decks/data/full.RData)

<!--- 


How To Obtain Data from Factbook:
- [Factbook Tutorial](data/data_file_2014.html)
-->


# Resources

This case study draws on materials developed in Chapter 11 of Data Science in R: A Case Studies Approach to Computational Reasoning and Problem Solving by Nolan and Temple Lang (free e-book through Duke Libraries)

[Use these instructions](decks/tableaudownload.html) to download Tableau.

[Tableau Cheat Sheet](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=5&ved=2ahUKEwjBkIbfy7DdAhUD3VMKHZPjCfYQFjAEegQIARAC&url=https%3A%2F%2Fconfluence.umd.edu%2Fdownload%2Fattachments%2F548635432%2FTableau%2520Cheat%2520Sheet%252010-31-2016.pdf%3Fversion%3D1%26modificationDate%3D1484239006000%26api%3Dv2&usg=AOvVaw0M6Y3DNPKOZc3XtNlkVrHz)

[Fancy Tableau Options](https://www.tableau.com/about/blog/2017/10/7-tips-and-tricks-dashboard-experts-76821)


# Reports

- Interim report: outline the general story you wish to tell graphically. Data sources and variables to be used in the data visualizations, along with short descriptions (e.g., captions) for planned visualizations, should also be included. Maximum of 3 pages.

- Final report:  in-class presentation (5 minutes), R/Tableau visualizations, and a two-page document that clearly references data sources, provides a rationale for the data chosen to tell the story, and summarizes the story told in the graphics.


# Slides 

[Healthy babies](decks/cs01_1_deck.html)

[Data visualization in R](decks/cs01_2_deck.html) 

[R code for September 5](decks/sept5tutorial.html)

[Mapping in R](decks/cs01_3_deck.html)

[Introduction to Tableau](decks/cs01_4_deck.html)

[Creating a Tableau Dashboard](decks/cs01_5_deck.html)

