---
title: "Case Study 2: Modeling"
---

```{r, echo=FALSE, include=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)
```


# Learning Objectives

- understand fitting and interpretation of general linear models
- understand situations in which standard models and methods may be inappropriate
- define and identify "small sample" situations in a variety of contexts
- gain skills to select and apply a variety of small sample statistical methods for analysis
- gain skills to understand consequences of small samples at the design stage of a project


# Case Study Goals

- explore factors related to birth weight in NC

- characterize factors related to infant mortality in NC on a statewide level, including exploration of time trends 

- determine whether infant mortality in specific racial and ethnic groups is level, declining, or on the rise


# Data 

We'll use the North Carolina birth and infant death data on Sakai for this assignment.


# Resources 
- [Linear Regression in R](http://r-statistics.co/Linear-Regression.html)
- [Logistic Regression in R](https://stats.idre.ucla.edu/r/dae/logit-regression/)
- [Power Analysis in R](https://www.statmethods.net/stats/power.html)
- [R Code for Some Nonparametric Tests](https://www.statmethods.net/stats/nonparametric.html)
<!---
- [Exact Logistic Regression in R](https://stats.idre.ucla.edu/r/dae/exact-logistic-regression/)
--->


# Reports 

- In an interim report due October 3, create a model to describe how factors available in the NC births file are related to birth weight of infants. Be sure to describe your model and modeling approach clearly and to present results in language suitable for publication in a scientific journal. Graphical displays are encouraged. The report is not to exceed 5 pages.

- In a final report due October 12, examine the factors related to statewide infant mortality rates (not including county of residence as a predictor) and evaluate whether there is evidence that these rates are changing over time in any specific groups. This report is also not to exceed 5 pages.

The case study grade will be based on both reports.




# Slides

- [Linear regression](decks/cs02_1_deck.html)

- [Logistic regression](decks/cs02_2_deck.html) 

- [Power analysis](decks/cs02_3_deck.html)
