---
title: "Case Study 3: Hierarchical Models"
---

```{r, echo=FALSE, include=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)
```


# Learning Objectives

- identify situations in which the generalized linear model (GLM) should be used for analysis 
- fit and interpret results of GLM's for binary and count data
- understand shrinkage and when hierarchical models may be useful in estimation
- fit, interpret, and illustrate results from hierarchical models


# Case Study Goals 

The goal of this case study is to examine county-specific infant mortality rates as a function of race/ethnicity.


# Data 

The data from this case study are simulated data (based on real data but generated randomly to eliminate risk of disclosure). The background is that a large HMO wants to know what patient and physician factors are most related to whether a patient’s lung cancer goes into remission after treatment as part of a larger study of treatment outcomes and quality of life in patients with lung cancer.

- [Simulated lung cancer data](https://stats.idre.ucla.edu/stat/data/hdp.csv)


# Resources

- [Logistic Regression in R](https://stats.idre.ucla.edu/r/dae/logit-regression/)
- [Introduction to Multilevel Models in R](https://rpubs.com/rslbliss/r_mlm_ws)
- Gelman and Hill, Data Analysis Using Regression and Multilevel/Hierarchical Models
- [Introduction to GLMMs](https://stats.idre.ucla.edu/other/mult-pkg/introduction-to-generalized-linear-mixed-models/)
- [Details on Example from IDRE](https://stats.idre.ucla.edu/r/dae/mixed-effects-logistic-regression/)

# Reports

- Create an interactive visualization in Tableau to show how infant mortality varies across counties, race/ethnicity groups, and time in NC. Visualizations will be presented in class on October 26. This visualization will be included in your final report.

- In a final report due November 14, examine the factors related to infant mortality rates and obtain estimated infant mortality rates for each county, year, and race/ethnicity group using a multilevel model. Write out the model you used in mathematical notation, and incorporate your estimated rates in a Tableau visualization for comparison with that you generated in the interim report. This report is not to exceed 5 pages. Reproducible code for fitting the model should be uploaded along with the report.

The case study grade will be based on the final report.



# Slides 

- [Linear multilevel models](decks/cs03_1_deck.html)

- [Multilevel logistic regression](decks/cs03_2_deck.html)

