---
title: "Case Study 4: Longitudinal Data"
---

```{r, echo=FALSE, include=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)
```


# Learning Objectives

- understand differences in inferences possible when using cross-sectional versus longitudinal data
- fit and interpret generalized linear mixed effects models for longitudinal data
- fit and interpret models fit using generalized estimating equations
- understand types of missing data, their potential consequences, and appropriate methods for handling missing data in a variety of settings


# Case Study Goals 


Case study 4 will involve analysis of a subset of data from [SHARE Child Pakistan](https://globalhealth.duke.edu/projects/share-child-pakistan), a DGHI study of children born in rural Pakistan, half to perinatally depressed mothers and half to  perinatally non-depressed mothers. Our data are on the mother's depression status (measured by PHQ-9 scores $\geq 10$) during the third trimester of pregnancy, and at 3 and 6 months postnatally. Our goal is to examine patterns in depression over time to see if depression levels are relatively constant, increasing, or decreasing. In addition, we are interested in  whether depression levels, or their changes over time, are related to maternal education and age.




# Data 

In this case study we consider a subset of data from the DGHI [SHARE Child Project](https://globalhealth.duke.edu/projects/share-child-pakistan) in Pakistan. These data, which have been approved for class use only and should be kept confidential, are available on the Sakai website. These data were generously provided by Dr. Asia Maselko, who moved from DGHI to UNC in 2016, and John Gallis in the DGHI Research Design and Analysis Core.


# Resources

- [Applied Longitudinal Analysis](https://www.wiley.com/en-us/Applied+Longitudinal+Analysis%2C+2nd+Edition-p-9780470380277): my favorite book on the topic, which is unfortunately focused on computation in SAS



# Reports 

In a report due November 30, describe trends in depression over time and whether these trends, or depression levels more generally, are related to maternal age and educational level. Because some women dropped out of the study, explore patterns of missing data and comment on their potential to affect inferences based on these data.


# Slides

- [Longitudinal versus Cross-Sectional Data](decks/cs04_1_deck.html)
- [Generalized estimating equations](decks/cs04_2_deck.html)
- [Missing data](decks/cs04_3_deck.html)
