---
title: " "
output: 
  html_document:
    toc_float: true
  
---

---
title: "STA 440: Case Studies in the Practice of Statistics"
description: "Students apply statistical analysis skills to in-depth data analysis projects ranging across diverse application areas including politics, information and culture, the environment, social science, global health, and health disparities. Students practice cutting-edge statistical methods and communicate their results both technically and non-technically via presentations and written reports. Prerequisite: STA360 or instructor permission. QS, R, W"
markup: "mmark"
---


### Lectures

<font color="#6CA0DC"><i class="fas fa-university fa-lg"></i></font> &nbsp; Perkins 071 

<font color="#6CA0DC"><i class="fas fa-calendar-alt fa-lg"></i></font> &nbsp; WF 11:45 - 1:00


### Teaching team and office hours 

| Team member | Office hours | Location |
| ----------  | ----         | ---- |
| [Professor Amy Herring](https://stat.duke.edu/people/amy-h-herring)  <a href="mailto:amy.herring@duke.edu" title="email"><i class="fa fa-envelope"></i></a> &nbsp;  | Wed and Thurs 1:30-2:30pm | 208 Old Chemistry |
[TA Alex Mang](https://stat.duke.edu/people/alexander-mang-0)  <a href="mailto:alexander.mang@duke.edu" title="email"><i class="fa fa-envelope"></i></a> &nbsp; | Wed 6:00 - 8:00 pm ??? | 211A Old Chemistry
 [TA TBA](https://lindsayberry.github.io)  <a href="mailto:lindsay.berry@duke.edu" title="email"><i class="fa fa-envelope"></i></a> &nbsp;  | Tue 1-2pm?? | 211A Old Chemistry
 
                  


### Materials

You should have access to a laptop and bring it to every class, fully charged. Texts and readings will be assigned as needed. Required software packages include R/RStudio (free) and Tableau (free for students).


### Topics and Important Dates
|Date           |Topic                      |Deliverables     |
| ----------    | -----------------         | --------------- |
| August 29     | Welcome, Groups, and CS1: Birth Weight        | Regression warm-up (in class)        |
| August 31     | CS1: Robust Regression    |                 |
| September 5   | CS1: Modeling in Class | |
| September 7   | CS1: Causal Inference | CS1 Interim Report: Model Development and Evaluation |
| September 12  | CS2: Visualizing our World in Data | |
| September 14  | CS2: Tableau | CS1 Final Report: Smoking and Birth Weight |
| September 19  | CS2: Tableau | |
| Septmeber 21  | CS3: Hierarchical Models: Birth Weight Disparities | |
| September 26  | Group Presentations of CS2 | CS2 Final Report: Our World in Data |
| Septmeber 28  | CS3: Multilevel Models: Time Trends | |
| October 3     | CS3: Generalized Linear Mixed Effects Models | CS3 Interim Report: Infant Mortality Visualization| 
| October 5     | CS3: Bayesian Hierarchical Models | Midsemester Grades Due (my deliverable)  & CS4 Evaluation Criteria |
| October 10    | CS4: Election Forecasting | CS3 Interim Report: County-Specific Mortality by Group|
| October 12    | CS4: Election Forecasting with "Mr. P" | |
| October 17    | CS4: Who Votes in NC? | CS3 Final Report: Infant Mortality Trends |
| October 19    | CS4: Election Modeling Workshop | |
| October 24    | CS4: Presentations: Who Votes in NC? | CS4 Interim Report: Who Votes in NC? |
| October 26    | Individual CS: Web Scraping | | 
| October 31    | Individual CS: Web Scraping | | CS4 Interim Report: Election Prediction Models |
| November 2    | Individual CS: Web Scraping Work in Groups | CS4 Final Report due by Midnight Nov 5|
| November 7    | CS4: Presentations: Post Election Diagnostics | Individual CS Interim Report: Analysis Plan  |
| November 9    | CS5: Missing Data: How to Survive | |
| Movember 14   | CS5: Missing Data | |
| November 16   | CS5: Missing Data | CS5 Interim Report: Patterns of Missing Data |
| November 28   | CS Lab | Individual CS Draft Report | 
| November 30   | Individual CS Q&A | CS5: Final Report |
| December 5    | Individual Presentations | Individual Reports Due |
| December 7    | Individual Presentations | Individual Reports Due |
| December 13, 2-5pm   | Individual Presentations | Individual Reports Due |

